---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dashboard"
subtitle: "Everyday is a brand new day!"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

message:
  style: "is-link" # See https://bulma.io/documentation/components/message/#colors for styling options.
  url: https://v1.jinrishici.com/all
  icon: "fas fa-bolt"
  mapping:
    title: 'origin'
    content: 'content'
  refreshInterval: 100000

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "My Homepage"
    icon: "fas fa-home"
    url: "https://www.lkwplus.com/"
    target: "_blank" # optional html tag target attribute
  - name: "My Blog"
    icon: "fas fa-blog"
    url: "https://blog.lkwplus.com/"
    target: "_blank" # optional html tag target attribute
  - name: "My GitHub"
    icon: "fab fa-github"
    url: "https://github.com/synthpop123/"
    target: "_blank" # optional html tag target attribute
  - name: "Edit Config"
    icon: "fas fa-edit"
    url: "https://github.com/synthpop123/homer/edit/main/public/assets/config.yml"
    target: "_blank" # optional html tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-film"
    items:
      - name: "Whatbox"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/whatbox.png"
        subtitle: "An app hosting platform"
        tag: "web"
        url: "https://whatbox.ca/manage"
        target: "_blank" # optional html a tag target attribute
      - name: "Plex"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/plex.png"
        subtitle: "Stream movies & TV shows"
        tag: "web"
        url: "https://app.plex.tv/desktop/#!/"
        target: "_blank" # optional html a tag target attribute
      - name: "Tautulli"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/tautulli.png"
        subtitle: "Monitor & analyze Plex Media Server"
        tag: "app"
        url: "http://elara.whatbox.ca:11574/home"
        target: "_blank" # optional html a tag target attribute
      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/radarr.png"
        subtitle: "Automated movie collection manager"
        tag: "app"
        url: "http://elara.whatbox.ca:31109/"
        target: "_blank" # optional html a tag target attribute
      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/sonarr.png"
        subtitle: "Automated TV collection manager"
        tag: "app"
        url: "http://elara.whatbox.ca:10719/"
        target: "_blank" # optional html a tag target attribute
      - name: "Overseerr"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/overseerr.png"
        subtitle: "Manage requests for media library"
        tag: "app"
        url: "http://elara.whatbox.ca:11213/"
        target: "_blank" # optional html a tag target attribute
  - name: "Piracy"
    icon: "fas fa-download"
    items:
      - name: "ruTorrent"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/rutorrent.png"
        subtitle: "A web front-end for rTorrent"
        tag: "app"
        url: "https://elara.whatbox.ca/webui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Deluge"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/deluge.png"
        subtitle: "A full-featured client with frontends"
        tag: "app"
        url: "http://elara.whatbox.ca:28038/"
        target: "_blank" # optional html a tag target attribute
      - name: "SABnzbd"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/sabnzbd.png"
        subtitle: "A Usenet newsreader and downloader"
        tag: "app"
        url: "http://elara.whatbox.ca:31365/sabnzbd/"
        target: "_blank" # optional html a tag target attribute
      - name: "pyLoad"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/pyload.png"
        subtitle: "A download manager for some websites"
        tag: "app"
        url: "http://elara.whatbox.ca:12389/dashboard"
        target: "_blank" # optional html a tag target attribute
      - name: "The Lounge"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/thelounge.png"
        subtitle: "A web-based IRC client"
        tag: "app"
        url: "http://elara.whatbox.ca:11995/#/"
        target: "_blank" # optional html a tag target attribute
      - name: "Cloudreve"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/cloudreve.png"
        subtitle: "Self-hosted file management system"
        tag: "app"
        url: "http://elara.whatbox.ca:18484/home?path=%2F"
        target: "_blank" # optional html a tag target attribute
  - name: "Indexer"
    icon: "fas fa-seedling"
    items:
      - name: "Prowlarr"
        logo: "https://cdn.jsdelivr.net/gh/NX211/homer-icons@master/png/prowlarr.png"
        subtitle: "An Indexer manager/proxy"
        tag: "app"
        url: "http://elara.whatbox.ca:14039/"
        target: "_blank" # optional html a tag target attribute
      - name: "autobrr"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/autobrr.png"
        subtitle: "Monitor IRC to get releases"
        tag: "app"
        url: "http://elara.whatbox.ca:16267/"
        target: "_blank" # optional html a tag target attribute
      - name: "PassThePopcorn"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/passthepopcorn.png"
        subtitle: "The greatest movie tracker"
        tag: "web"
        url: "https://passthepopcorn.me/index.php"
        target: "_blank" # optional html a tag target attribute
      - name: "HDBits"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/hdbits.png"
        subtitle: "The greatest HD tracker"
        tag: "web"
        url: "https://hdbits.org/browse.php"
        target: "_blank" # optional html a tag target attribute
      - name: "Cinemageddon"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/cinemageddon.png"
        subtitle: "Tracker dedicated in old & rare movies"
        tag: "web"
        url: "https://cinemageddon.net/browse.php"
        target: "_blank" # optional html a tag target attribute
      - name: "BeyondHD"
        logo: "https://cdn.jsdelivr.net/gh/synthpop123/imagebed@master/img/beyondhd.me.png"
        subtitle: "Great HD tracker with high quality standards"
        tag: "web"
        url: "https://beyond-hd.me/torrents"
        target: "_blank" # optional html a tag target attribute
